# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: the mango zone
email: mangodotpdf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    memes
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mangopdf
github_username:  mangopdf
show_drafts: false
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

long_text: "These are used to personalize your new site. If you look in the HTML files,
 you will see them accessed via ite.title and so on.
 You can create any custom variable you would like, and they will be accessible
 in the templates via ."

con_description_short: "PurpleCon is a con you can attend. This is about how long this text should be."
con_description_long: "Purplecon is a fully sick, lactose free, nintendo-certified DLC for your Nintendo GameBoy console. Join Grace and the gang on another adventure this Spring, travelling to new and exciting worlds in search of the legendary Fountain of Lychee Jelly."
logo_url: "https://example.com/logo"

# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
