# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: purplecon
email: us@purplecon.nz
description: >- # this means to ignore newlines until "baseurl:"
    a nice place for infosec friends to be friends
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: purplecon
github_username:  purplecon
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


logo_url: "https://example.com/logo"

con_heading: "purplecon"
con_description_short: "purplecon is a cool and trendy event for defenders and developers to share actionable security wisdom in a safe and inclusive environment. purplecon 2018 is $100% real and you are invited."
what_does_purplecon_want: "Your favourite stories about helping people build stuff that’s Strong vs Hackers. Developers writing secure code, security team helping ship it, server warlocks running it. Anything that keeps people safe."
why_is_purplecon: "We just thought it would be Good."
can_purplecon_be_a_jp: "heck yeah we love justice"
where_when: "15 November 2018. The goddAmn Michael Fowler Centre. Wellington, New Zealand."
can_i_be_a_purplecon: "Have yourself a browse of the <a href=\"/cfp\">CFP</a>."
is_purplecon_gateway_cloud: "log in, become a presenter, everybody to the data centre"
tickets_description: "Seats will be limited due to venue size, so we will be live-streaming and recording talks so everyone can join in. Please enter your details <a href=\"https://goo.gl/forms/fJS9Ji795F48f5X53\">here</a> to be notified when tickets are available."
who_is_it_for: "Developers, Students, Security People, Nurses, The Illuminati, Elves, Level 8 Wizards. Anyone who wants to learn about defensive computer security."
cfp_description: "Want to talk at purplecon? Come on down to <a href=\"/cfp\">CFP</a> town. Do <em>not</em> actually send us physical papers. We don't know what to do with them. 
    We <em>do</em> want speakers to submit some kind of document with their talk. This way, when someone wants to <em>actually</em> use your limitless interdimensional knowledge, they have something to refer to."
conduct_description: "Everyone attending is expected to follow our <a href=\"/conduct\">Code of Conduct</a>. This means a lot to us and we're not messing around."
cfp_link: "https://goo.gl/forms/OrqCEm43zyhY8SUW2"


